// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChatReq struct {
	Question string `json:"question"`
}

type ChatResp struct {
	Answer string `json:"answer"`
}

type Empty struct {
}

type LoginReq struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`  // JWT Token
	AccessExpire int64  `json:"access_expire"` // 过期时间戳
	Role         string `json:"role"`          // 角色：admin | recruiter | guest
}

type ResumeResp struct {
	Name        string   `json:"name"`
	Phone       string   `json:"phone"` // 招聘者可见，公开不可见
	Experience  []string `json:"experience"`
	DownloadUrl string   `json:"download_url"`
}
