// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package auth_client

import (
	"context"

	"auth-rpc/pb/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest     = auth.LoginRequest
	LoginResponse    = auth.LoginResponse
	UserInfoRequest  = auth.UserInfoRequest
	UserInfoResponse = auth.UserInfoResponse

	Auth interface {
		// 验证登录
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultAuth struct {
		cli zrpc.Client
	}
)

func NewAuth(cli zrpc.Client) Auth {
	return &defaultAuth{
		cli: cli,
	}
}

// 验证登录
func (m *defaultAuth) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultAuth) GetUserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := auth.NewAuthClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
