// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package server

import (
	"context"

	"auth-rpc/internal/logic"
	"auth-rpc/internal/svc"
	"auth-rpc/pb/auth"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

// 验证登录
func (s *AuthServer) Login(ctx context.Context, in *auth.LoginRequest) (*auth.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 获取用户信息
func (s *AuthServer) GetUserInfo(ctx context.Context, in *auth.UserInfoRequest) (*auth.UserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
