// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	protected "gateway-api/internal/handler/protected"
	public "gateway-api/internal/handler/public"
	"gateway-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// AI 对话接口 (未来功能)
				Method:  http.MethodPost,
				Path:    "/chat",
				Handler: protected.ChatHandler(serverCtx),
			},
			{
				// 验证 Token 是否有效 (前端保活)
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: protected.PingHandler(serverCtx),
			},
			{
				// 获取完整简历 (仅限登录用户)
				Method:  http.MethodGet,
				Path:    "/resume",
				Handler: protected.GetResumeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 简单的自我介绍 (公开)
				Method:  http.MethodGet,
				Path:    "/intro",
				Handler: public.GetIntroHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: public.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/public"),
	)
}
