apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: arc-gateway-api:v1.0 # 建议带上具体版本号
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-svc
spec:
  type: NodePort
  selector:
    app: gateway-api
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30088